# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.8
  allowed_goal_duration_margin: 0.8
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - r12_arm_controller


  r12_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - waist_joint
      - shoulder_joint
      - elbow_joint
      - hand_joint
      - wrist_joint
    action_ns: follow_joint_trajectory
    default: true
  
